### ISSUE TITLE
Incorrect bounds on binary variables

### ISSUE THREAD

**Issue by mlubin** [JuliaSmoothOptimizers/QPSReader.jl#28]
While integer variables are not supported, the code claims to at least set their bounds. However, the reader can silently give incorrect bounds.

The [CPLEX MPS documentation](http://plato.asu.edu/cplex_mps.pdf) says:

> ILOG CPLEX accepts two commonly used ways of extending
the MPS file format to include integer variables: in the COLUMNS section or in the BOUNDS
section.
> In the first way, integer variables are identified within the COLUMNS section of the MPS file
by marker lines. 
> ...
> If no bounds are specified for the variables within markers, bounds of 0 (zero) and 1 (one)
are assumed.

GLPK follows the CPLEX behavior. 

However, QPSReader ignores markers, so it can't can't enforce this rule to set the correct variable bounds (it sets an upper bound of infinity in this case).

**Comment by mtanneau** [comment]
Indeed. Gurobi also follows the same convention: [Gurobi MPS format](https://www.gurobi.com/documentation/9.0/refman/mps_format.html).

Since fixing this requires to not ignore markers anymore, I will add support for integer variables at the same time.
I can't work on this until next week though.

**Comment by mtanneau** [comment]
So, it seems there are a few additional details, and not all solvers appear to do the same.

* Variable is marked integer, but there is a `BV`/`UI`/`LI` entry in the `BOUNDS` section.
In that case, the default `[0, 1]` bounds are discarded in favor of entries in the `BOUNDS` section.
Gurobi and Mosek seem to both follow that convention.
* Several bounds are specified in the `BOUNDS` section.
  * CPLEX: error (according to [docs](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.9.0/ilog.odms.cplex.help/CPLEX/FileFormats/topics/MPS_records.html))
  * Gurobi: record first entry read, discard the subsequent bounds and print a warning
  * Mosek: record last entry, no warning

@dpo @mlubin, the convention should look like this:

| Marker? | `BOUNDS` fields | Type | Bounds reported |
|:--:|:--:|:--:|:--:|
| Yes | - | Integer | `[0, 1]` 
| Yes | `BV` | Binary | `[0, 1]` 
| Yes | (`LI`, `l`) | Integer | `[l, Inf]` 
| Yes | (`UI`, `u`) | Integer | `[0, u]` 
| Yes | (`LI`, `l`) + (`UI`, `u`) | Integer | `[l, u]` 
| No | `BV` | Binary | `[0, 1]` 
| No | (`LI`, `l`) | Integer | `[l, Inf]` 
| No | (`UI`, `u`) | Integer | `[0, u]` 
| No | (`LI`, `l`) + (`UI`, `u`) | Integer | `[l, u]` 

In particular, using `UP`/`LO` instead of `UI`/`LI` does not affect the final bounds. The latter only results in the corresponding variable being integer.

Regarding the multiple entries, doing like Mosek, i.e., having subsequent entries erase previous ones, is the simplest.

**Comment by mtanneau** [comment]
There's actually another convention, independent of integrality, regarding negative upper bounds.
The following is from [CPLEX documentation](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.10.0/ilog.odms.cplex.help/CPLEX/FileFormats/topics/MPS_records.html). Gurobi appears to behave the same way, though no mention is made in the [Gurobi documentation](https://www.gurobi.com/documentation/9.0/refman/mps_format.html). Mosek appears to keep a lower bound of 0.

> If no bounds are specified, CPLEX assumes a lower bound of 0 (zero) and an upper bound of +∞.
> If only a single bound is specified, the unspecified bound remains at 0 or +∞, whichever applies, with one exception. If an upper bound of less than 0 is specified and no other bound is specified, the lower bound is automatically set to -∞.
> CPLEX deviates slightly from a convention used by some MPS readers when it encounters an upper bound of 0 (zero). Rather than automatically set this variable’s lower bound to -∞, CPLEX accepts both a lower and upper bound of 0, effectively fixing that variable at 0. CPLEX resets the lower bound to -∞ only if the upper bound is less than 0.
> A warning message is issued when this exception is encountered.

Given that there is no clear consensus on this, I am tempted to keep the current status-quo, i.e., unspecified lower bounds are `0` and unspecified upper bounds are `Inf`.

**Comment by mlubin** [comment]
> If only a single bound is specified, the unspecified bound remains at 0 or +∞, whichever applies, with one exception. If an upper bound of less than 0 is specified and no other bound is specified, the lower bound is automatically set to -∞.

I think this part is relatively standard. The divergence in implementations comes up when there's an upper bound of zero and no lower bound.

It's easy to get lost in the inconsistencies in MPS. I think a good concrete target is to be able to handle the corner cases that are present in a standard benchmark set like MIPLIB 2017. Everyone agrees that these instances should parse correctly, and if they don't, someone is likely to open a bug about it sometime in the future.

**Comment by mtanneau** [comment]
Closed by #31
